version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["gunicorn", "store.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis
  db:
    image: postgres
    env_file:
      - .env
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app worker --loglevel=info
    depends_on:
      - app
    env_file:
      - .env
